[workspace]

members = [
    "bloody_song",
    "company_directory",
    "fibonacci" ,
    "file_handler",
    "first_word", "forest",
    "guessing_game",
    "ip_address",
    "maths", 
    "messenger",
    "minigrep",
    "pig_latin",
    "restaurant",
    "temp_conv"
]

resolver = "2"
